In [145]:
import numpy as np

# Creating Arrays

In [146]:
arr = np.array([1,2,3]) # create array from List/tuple
arr1 = np.array((1,2,3))

In [147]:
print(arr)
print(arr1)

[1 2 3]
[1 2 3]


In [148]:
zeros = np.zeros((2,2)) # create array of all zeros

In [149]:
print(zeros)

[[0. 0.]
 [0. 0.]]


In [150]:
ones = np.ones((2,3)) # create array of all onec

In [151]:
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [152]:
emp = np.empty((2,2)) # create empty array -> not empty but dont take memory

In [153]:
print(emp)

[[0. 0.]
 [0. 0.]]


In [154]:
a = np.arange(0,10,2) # create array within range with step size

In [155]:
print(a)

[0 2 4 6 8]


In [156]:
b = np.linspace(0,1,5) # create array within range with evenly spaced value

In [157]:
print(b)

[0.   0.25 0.5  0.75 1.  ]


In [158]:
I = np.eye(3) # Identity Matrix

In [159]:
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [160]:
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [161]:
r = np.random.rand(2,3)  # random value between 0 and 1
print(r)

[[0.47066075 0.18017911 0.07906807]
 [0.73796725 0.72937599 0.34652955]]


In [162]:
ri = np.random.randint(1,10,(2,3)) # random integer in given ranger
print(ri)

[[8 1 9]
 [1 3 5]]


# Array Indexing & Slicing

In [163]:
arr = np.array([[10,20,30,40],
                [50,60,70,80],
                [90,100,110,120]])
print(arr)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


+ve Indexing

In [164]:
print(arr[1,1])

60


In [165]:
print(arr[2,3])

120


-ve Indexing

In [166]:
print(arr[-1,-1])

120


In [167]:
print(arr[-2,-3])

60


Row Selection

In [168]:
arr[0,:]

array([10, 20, 30, 40])

Column Selection

In [169]:
arr[:,0]

array([10, 50, 90])

Slicing

In [170]:
arr[0:2,0:3]

array([[10, 20, 30],
       [50, 60, 70]])

Step Slicing

In [171]:
arr[::2,:]

array([[ 10,  20,  30,  40],
       [ 90, 100, 110, 120]])

In [172]:
arr[:,::2]

array([[ 10,  30],
       [ 50,  70],
       [ 90, 110]])

# Fency Indexing

In [173]:
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [174]:
arr[[0,2],[1,3]] 
# [0,2] --> rows indexing & [1,3] --> columns indexing
# not [0,2] --> 0 row , 2 column 

array([ 20, 120])

Boolean Indexing

In [175]:
arr > 50 # return boollean array with True for Value greater than 50 else False

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

# Array Operations

In [176]:
a = np.array([[5,6,8],
              [1,2,3]])
b = np.array([[1,2,6],
              [1,1,1]])

Arithmetic Operation

In [177]:
print(a + b)

[[ 6  8 14]
 [ 2  3  4]]


In [178]:
print(a-b)

[[4 4 2]
 [0 1 2]]


In [179]:
print(a * b)

[[ 5 12 48]
 [ 1  2  3]]


In [180]:
print(a // b)

[[5 3 1]
 [1 2 3]]


In [181]:
print(a / b)

[[5.         3.         1.33333333]
 [1.         2.         3.        ]]


In [182]:
print(a % b)

[[0 0 2]
 [0 0 0]]


In [183]:
print(a ** b)

[[     5     36 262144]
 [     1      2      3]]


Comparison Operation

In [184]:
a > b

array([[ True,  True,  True],
       [False,  True,  True]])

In [185]:
a < b

array([[False, False, False],
       [False, False, False]])

In [186]:
a >= b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [187]:
a <= b

array([[False, False, False],
       [ True, False, False]])

In [188]:
a == b

array([[False, False, False],
       [ True, False, False]])

In [189]:
a != b

array([[ True,  True,  True],
       [False,  True,  True]])

Broadcasting

In [190]:
a = np.array([1,2,3])
b = 10

print(a+b)

[11 12 13]


# Mathematical & Statistical Functions

1 Basic Aggregation Functions

In [191]:
a = np.array([1,3,4,5,8,0,12,14,3,4,5])

print(np.sum(a))

59


In [192]:
np.mean(a)

np.float64(5.363636363636363)

In [193]:
np.median(a)

np.float64(4.0)

In [194]:
np.min(a)

np.int64(0)

In [195]:
np.max(a)

np.int64(14)

In [196]:
index = np.argmin(a)
print(index)
print(a[index])

5
0


In [197]:
indexmax = np.argmax(a)
print(indexmax)
print(a[indexmax])

7
14


2 Statistical Functions

In [198]:
np.std(a)

np.float64(4.140108195176618)

In [199]:
np.var(a)

np.float64(17.140495867768593)

In [200]:
print(np.percentile(a,25))
print(np.percentile(a,75))

3.0
6.5


3 Axis - wise Operations

In [201]:
a = np.array([[1,2,3],
              [4,5,6]])

In [202]:
np.sum(a,axis=0)

array([5, 7, 9])

In [203]:
np.sum(a,axis=1)

array([ 6, 15])

# Reshaping & Matrix Operations

1 Reshaping Arrays

In [204]:
arr = np.array(np.arange(1, 13))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [205]:
arr2 = arr.reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [206]:
arr3 = arr.reshape(3,2,2) # 3 matrix of 2x2
arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

2 Flattening Arrays

In [207]:
arr = np.array(([1, 2, 3], [4, 5, 6]))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [208]:
a = arr.flatten()
a

array([1, 2, 3, 4, 5, 6])

In [209]:
a[4] = 10
a

array([ 1,  2,  3,  4, 10,  6])

In [210]:
arr # Modifying the output never affects the original array.

array([[1, 2, 3],
       [4, 5, 6]])

In [211]:
r = arr.ravel()
r

array([1, 2, 3, 4, 5, 6])

In [212]:
r[4] = 10
r

array([ 1,  2,  3,  4, 10,  6])

In [213]:
arr # Modifying the output may change the original array

array([[ 1,  2,  3],
       [ 4, 10,  6]])

3 Transpose

In [214]:
arr

array([[ 1,  2,  3],
       [ 4, 10,  6]])

In [215]:
arr.T

array([[ 1,  4],
       [ 2, 10],
       [ 3,  6]])

4 Concatenate

In [216]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [217]:
d = np.array([9,10,11,12])
e = np.concatenate((a,d),axis = 0)
e

array([ 1,  2,  3,  4,  9, 10, 11, 12])

In [218]:
f = np.concat((a,d))

In [219]:
f

array([ 1,  2,  3,  4,  9, 10, 11, 12])

In [220]:
print(np.__version__)

2.3.5


In [221]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

v = np.concat((a, b), axis=0)
v


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [222]:
h = np.concat((a, b), axis=1)
h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

For concatenation to work, the arrays must have the exact same size along every axis except the one you are joining.
* If you use axis=0, the arrays must have matching numbers of columns.
* If you use axis=1, the arrays must have matching numbers of rows.

If they don't match, Python will throw a ValueError.

5 Stack

In [223]:
a = np.array([1,2,3])
b = np.array([4,5,6])

v = np.stack((a,b), axis=0)
v


array([[1, 2, 3],
       [4, 5, 6]])

In [224]:
h = np.stack((a,b), axis=1)
h

array([[1, 4],
       [2, 5],
       [3, 6]])

6 Split

In [225]:
arr = np.array ([1, 2,3,4,5,6])
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [226]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [227]:
np.hsplit(arr2, 2) # means cutting it down the middle along the columns.

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [228]:
np.vsplit(arr2, 2) # means cutting it across the rows 

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

7 Matrix Multiplication

In [229]:
A = np.array(([1, 2], [3, 4]))
B = np.array([[5, 6], [7, 8]])


In [230]:
A

array([[1, 2],
       [3, 4]])

In [231]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A @ B # matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A,B) # matrix multiplication

array([[19, 22],
       [43, 50]])

In [234]:
A * B # Element wise multiplication

array([[ 5, 12],
       [21, 32]])

# Random Module

1 Random Numbers

In [ ]:
a = np.random.rand(2,3) # Uniform [0,1]
a

array([[0.58914955, 0.29473443, 0.93660324],
       [0.05944606, 0.35864319, 0.78962699]])

In [236]:
b = np.random.randn(2,3) # Standard Normalization (Mean 0, Std 1)
b

array([[-1.1305765 ,  0.55255152,  0.14140325],
       [-0.24225312,  0.75716352,  1.13413825]])

In [237]:
c = np.random.randint(1,10,(2,3)) # Random Integer
c

array([[3, 1, 3],
       [1, 6, 7]], dtype=int32)

2 Seed (Reproducibility)

In [240]:
np.random.seed(42)
print(np.random.rand(2,2)) #Same output every time

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


In [241]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
np.random.shuffle(arr) # elements shuffled
arr

array([4, 2, 5, 3, 1])

### Difference between np.array() and np.asarray()?

In [ ]:
a = np.array([1,2,3])

b = np.array(a) # np.array() generally creates a new array by default.


In [249]:
print(id(a))
print(id(b))

2009014833424
2009014831792


In [ ]:
c = np.asarray(a) # np.asarray() avoids making a copy when the input is already an ndarray with a compatible dtype

In [251]:
print(id(a))
print(id(c))

2009014833424
2009014833424


### broadcasting

In [254]:
a = np.array([[2],[3],[4]])

b = np.array([1,2,3,4])

a+b

array([[3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

NumPy compares array dimensions from right to left. Two dimensions are compatible when they are equal or one of them is 1.

(3, 1) 
        -> (3, 4)
(1, 4)

Equal dimensions or One dimension is 1 → compatible
Otherwise → broadcasting error

In [259]:
a = np.array([[3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

np.where(a > 5) 
# np.where() is used to find positions where a condition is true, or to choose values based on a condition.

(array([0, 1, 1, 2, 2, 2]), array([3, 2, 3, 1, 2, 3]))

In [260]:
np.where(a > 5, 1, 0) # vectorized if-else

array([[0, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 1, 1, 1]])

In [265]:
a = np.array([1,np.nan,2,3,4])

In [266]:
np.isnan(a)

array([False,  True, False, False, False])

In [267]:
b = a[~np.isnan(a)]
b

array([1., 2., 3., 4.])

In [269]:
np.nan_to_num(a)

array([1., 0., 2., 3., 4.])

In [277]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a,b)

np.int64(32)

In [278]:
np.matmul(a,b)

np.int64(32)

In [279]:
a = np.ones((2, 3, 4))
b = np.ones((2, 4, 5))

In [ ]:
a # 2 batch of (3 x 4) matrix

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
b # 2 batch of (4 x 5) matrix

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
c = np.matmul(a, b)

print(c.shape)  # (3 x 4) @ (4 x 5) -> (3 x 5)

(2, 3, 5)


In [283]:
d = np.dot(a,b)

print(d.shape)

(2, 3, 2, 5)


In [293]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [292]:
a[a == 0.] = 1
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [294]:
a = np.where(a == 0, 1, a)

In [295]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])