In [95]:
import numpy as np

# Creating Arrays

In [96]:
arr = np.array([1,2,3]) # create array from List/tuple
arr1 = np.array((1,2,3))

In [97]:
print(arr)
print(arr1)

[1 2 3]
[1 2 3]


In [98]:
zeros = np.zeros((2,2)) # create array of all zeros

In [99]:
print(zeros)

[[0. 0.]
 [0. 0.]]


In [100]:
ones = np.ones((2,3)) # create array of all onec

In [101]:
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [102]:
emp = np.empty((2,2)) # create empty array -> not empty but dont take memory

In [103]:
print(emp)

[[0. 0.]
 [0. 0.]]


In [104]:
a = np.arange(0,10,2) # create array within range with step size

In [105]:
print(a)

[0 2 4 6 8]


In [106]:
b = np.linspace(0,1,5) # create array within range with evenly spaced value

In [107]:
print(b)

[0.   0.25 0.5  0.75 1.  ]


In [108]:
I = np.eye(3) # Identity Matrix

In [109]:
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [110]:
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [111]:
r = np.random.rand(2,3)  # random value between 0 and 1
print(r)

[[0.56480316 0.78617688 0.21015731]
 [0.44063362 0.92583016 0.926255  ]]


In [112]:
ri = np.random.randint(1,10,(2,3)) # random integer in given ranger
print(ri)

[[9 1 2]
 [1 6 9]]


# Array Indexing & Slicing

In [113]:
arr = np.array([[10,20,30,40],
                [50,60,70,80],
                [90,100,110,120]])
print(arr)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


+ve Indexing

In [114]:
print(arr[1,1])

60


In [115]:
print(arr[2,3])

120


-ve Indexing

In [116]:
print(arr[-1,-1])

120


In [117]:
print(arr[-2,-3])

60


Row Selection

In [118]:
arr[0,:]

array([10, 20, 30, 40])

Column Selection

In [119]:
arr[:,0]

array([10, 50, 90])

Slicing

In [120]:
arr[0:2,0:3]

array([[10, 20, 30],
       [50, 60, 70]])

Step Slicing

In [121]:
arr[::2,:]

array([[ 10,  20,  30,  40],
       [ 90, 100, 110, 120]])

In [122]:
arr[:,::2]

array([[ 10,  30],
       [ 50,  70],
       [ 90, 110]])

# Fency Indexing

In [123]:
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [124]:
arr[[0,2],[1,3]] 
# [0,2] --> rows indexing & [1,3] --> columns indexing
# not [0,2] --> 0 row , 2 column 

array([ 20, 120])

Boolean Indexing

In [125]:
arr > 50 # return boollean array with True for Value greater than 50 else False

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

# Array Operations

In [130]:
a = np.array([[5,6,8],
              [1,2,3]])
b = np.array([[1,2,6],
              [1,1,1]])

Arithmetic Operation

In [131]:
print(a + b)

[[ 6  8 14]
 [ 2  3  4]]


In [132]:
print(a-b)

[[4 4 2]
 [0 1 2]]


In [133]:
print(a * b)

[[ 5 12 48]
 [ 1  2  3]]


In [135]:
print(a // b)

[[5 3 1]
 [1 2 3]]


In [136]:
print(a / b)

[[5.         3.         1.33333333]
 [1.         2.         3.        ]]


In [137]:
print(a % b)

[[0 0 2]
 [0 0 0]]


In [138]:
print(a ** b)

[[     5     36 262144]
 [     1      2      3]]


Comparison Operation

In [139]:
a > b

array([[ True,  True,  True],
       [False,  True,  True]])

In [140]:
a < b

array([[False, False, False],
       [False, False, False]])

In [141]:
a >= b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [142]:
a <= b

array([[False, False, False],
       [ True, False, False]])

In [143]:
a == b

array([[False, False, False],
       [ True, False, False]])

In [144]:
a != b

array([[ True,  True,  True],
       [False,  True,  True]])

Broadcasting

In [145]:
a = np.array([1,2,3])
b = 10

print(a+b)

[11 12 13]
