# Introduction to  NumPy

### NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering

### The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

In [1]:
import numpy as np

In [2]:
a = np.array([ [1,2,3],
             [4,5,6]])

In [3]:
a.shape

(2, 3)

### In NumPy, this idea is generalized to an arbitrary number of dimensions, and so the fundamental array class is called
### "ndarray": it represents an “N-dimensional array”.

## Most NumPy arrays have some restrictions. For instance:

### All elements of the array must be of the same type of data.
### Once created, the total size of the array can’t change.
### The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

In [5]:
n = np.array([1,2,3,4,5,6])

In [6]:
n[0]=10
n

array([10,  2,  3,  4,  5,  6])

### One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

In [8]:
b= n[3:] # return a view

In [9]:
b # view

array([4, 5, 6])

In [10]:
b[0] = 40 # chnages in view also chnage in original array

In [11]:
b

array([40,  5,  6])

In [14]:
n

array([10,  2,  3, 40,  5,  6])

### In 2D-list element access by a[0][0] but in numpy a[0,0]

In [15]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [16]:
arr[1,2]

np.int64(7)

In [17]:
arr.ndim

2

In [18]:
arr.shape

(3, 4)

In [19]:
arr.size

12

In [20]:
arr.dtype

dtype('int64')

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [41]:
np.ones(2)

array([1., 1.])

In [33]:
np.empty(2)

array([1., 1.])

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [38]:
np.linspace(0,10,num=5)  # give 5 number with equal spacing between

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
 # defoult data type is floating  point np.float64
np.ones(2,dtype=np.int64)

array([1, 1])

In [44]:
x=np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [45]:
np.sort(x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

#np.concatenate(a,b) # We receive an error because we failed to supply the matrices in the form of a tuple to the concatenate() function.
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])

np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
a= np.arange(1,10)

In [56]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b=a.reshape(3,3)

In [58]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
|